### ISSUE TITLE
create smb user via smb_user does not work

### ISSUE THREAD

**Issue by monotek** [kakwa/puppet-samba#34]
I try to add a smb user to samba classic via smb_user but when i run puppet i get the following error:

```
[root@centos backup]# puppet agent -tv
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for centos
Info: Applying configuration version '1490344835'
Error: Could not find a suitable provider for smb_user
Notice: Applied catalog in 18.18 seconds
```

**Comment by kakwa** [comment]
It will not work, it's only a resource used to add users in Samba 4 AD Domain Controller, that's why it's in the "Samba 4 AD Domain Controller" paragraph.

**Comment by monotek** [comment]
Ah. OK. Thanks... 
Maybe i'll try to add it to classic too.

**Comment by kakwa** [comment]
It doesn't make a lot of sense for "classic". In classic mode, samba is not a user directory service, it relies on various external directories (ldap, unix accounts, Active Directory...) to get the users.

At most, it maintains a mapping between "technical" account through idmap (let say for example between a unix account with its UID and an AD account with its SID).

**Comment by monotek** [comment]
Just wan't to have "smbpasswd -a" done by the module.
Otherwise you have to login on the server to set the password.

**Comment by kakwa** [comment]
could be interesting indeed, along with management of the smbusers file.

However, for this, a way to check the password is needed (in order to not run smbpasswd at every run).

I do something close for checking the password of the Administrator in DC mode:

https://github.com/kakwa/puppet-samba/blob/master/manifests/dc.pp#L287

It works well for the DC use case, but I've some difficulties to come-up with a more generic way for the smbpasswd use case.

Do you have an idea?
